language: ruby
bundler_args: --without development
script: "bundle exec rspec spec"
rvm:
  - 1.9.3
addons:
  code_climate:
    repo_token: 7bedfa0d127f4a10efba3e66e9af7cb566c6ed44b5c6ae7f2b0c8bf0be6de75f
