# Used to setting cookies/sessions
domain: 'env:app_domain'
# Used by Rack::Session::Cookie to encode/decode session information
session:
  secret: 'env:session_secret'
  old_secret: 'env:session_old_secret'
stripe:
  key: 'env:stripe_key'
  version: '2013-02-13'
transloadit:
  auth_key: 'env:transloadit_key'
  account_template_id: 'env:transloadit_account_template_id'
  vehicle_template_id: 'env:transloadit_vehicle_template_id'
