# Used to setting cookies/sessions
domain: 'domain.local'
# Used by Rack::Session::Cookie to encode/decode session information
session:
  secret: 'change me'
  old_secret: 'change me'
stripe:
  key: 'stripe_key from https://manage.stripe.com/account/apikeys'
  version: '2013-02-13'
  live: false
# Used by account details page to handle uploads
transloadit:
  auth_key: 'auth key from https://transloadit.com/accounts/credentials'
  account_template_id: 'template id from https://transloadit.com/templates'
  vehicle_template_id: 'template id from https://transloadit.com/templates'
