# Used to setting cookies/sessions
domain: 'domain.local'
# Used for passing messages between boxes/processes/workers
amqp:
  producer: 'amqp://user:pass@amqp.url:port/path'
  consumer: 'amqp://user:pass@amqp.url:port/path'
# Used for publishing to ebay
ebay:
  api_url: 'https://api.ebay.com/ws/api.dll | https://api.sandbox.ebay.com/ws/api.dll'
  sign_in: 'https://signin.ebay.com/ws/eBayISAPI.dll | https://signin.sandbox.ebay.com/ws/eBayISAPI.dll'
  appid: 'AppID from https://developer.ebay.com/DevZone/account/Default.aspx'
  certid: 'CertID from https://developer.ebay.com/DevZone/account/Default.aspx'
  devid: 'DEVID from https://developer.ebay.com/DevZone/account/Default.aspx'
  runame: 'RuName to use from https://developer.ebay.com/DevZone/account/Default.aspx'
# Used for sending emails
mailgun:
  domain: 'Domain name from https://mailgun.com/cp'
  from: 'Where the mails should say they are from'
  key: 'API Key from https://mailgun.com/cp'
  url: 'API URL from https://mailgun.com/cp without https://'
# Used by Rack::Session::Cookie to encode/decode session information
# These should be long, unique strings
session:
  secret: 'change me'
  old_secret: 'change me'
# Used for enabling money transactions with Stripe
stripe:
  key: 'secret key from https://manage.stripe.com/account/apikeys'
  pub_key: 'publishable key from https://manage.stripe.com/account/apikeys'
  version: '2013-02-13'
  live: false
# Used to handle file uploads
transloadit:
  auth_key: 'auth key from https://transloadit.com/accounts/credentials'
  account_template_id: 'template id from https://transloadit.com/templates'
  vehicle_template_id: 'template id from https://transloadit.com/templates'
