mongo:
  # NOTE: Adding uri to this will break specs because they need to test both
  # when it exists and when it doesn't
  host: '127.0.0.1'
  port: '27017'
  database: 'lynr_spec'
int_val: 1234
bool_val: true
false_val: false
string_val: 'hithere'
env_val: 'env:whereami'
str_bool_false: 'false'
str_bool_true: 'true'
int_bool_0: 0
int_bool_1: 1
